version: '3.7'
services:
  test:
    build:
      context: .
      target: dev
    command: cabal new-test
    volumes:
      - stack-work:/usr/local/src/.stack-work
      - .:/usr/local/src
    environment:
      - NB_LOGIN=$LOGIN
      - NB_PASSWORD=$PASSWORD
volumes:
  stack-work: {}
