version: '3.7'
services:
  test:
    build:
      context: .
      target: dev
    command: stack test
    volumes:
      # - stack-work:/usr/local/src/.stack-work
      - .:/usr/local/src
    environment:
      - LOGIN
      - PASSWORD
    depends_on:
      - redis
  redis:
    image: seriouscomp/rd_themis
    ports:
      - 6379:6379
volumes:
  stack-work: {}
